Projekt/ExampleMVC/Models/CartViewModel.cs
using Example.Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExampleMVC.Models
{
    public class CartViewModel
    {
        public CartViewModel(Product prod, int q) { product = prod; quantity = q; }
        public Product product{ get; set; }
        public int quantity { get; set; }
    }
}

Projekt/ExampleMVC/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Example.Entities;
using Example.Entities.Models;
using Example.DataAccessLayer.Repositories.Abstract;
using ExampleMVC.Models;

namespace ExampleMVC.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IProductRepository _productRepository;

        public OrdersController(IOrderRepository orderRepository, IProductRepository productRepository)
        {
            _orderRepository = orderRepository;
            _productRepository = productRepository;
        }

        // GET: Orders
        public async Task<ActionResult> Index()
        {
            List<CartViewModel> cart = (List<CartViewModel>)Session["cart"];
            if (cart == null)
            {
                ViewBag.Price = 0;
            }
            else ViewBag.Price = cart.Sum(b => b.product.Price);
            var orders = await _orderRepository.GetOrdersAsync();
            return View(orders);
        }

        // GET: Orders/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var order = await _orderRepository.GetOrderAsync(id.Value);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {            
            List<CartViewModel> cart = (List<CartViewModel>)Session["cart"];
            if (!Request.IsAuthenticated)
            { 
                ViewBag.User = ""; 
            }
            else ViewBag.User = User.Identity.Name;

            if (cart == null)
            {
                ViewBag.Price = 0;
            }
            else 
            {                
                ViewBag.Price = (int)cart.Sum(b => b.product.Price);
            }
            var order = new Order();
            order.Name = ViewBag.Name;
            order.TotalPrice = ViewBag.Price;
            return View(order);
        }

        // POST: Orders/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,TotalPrice")] Order order)
        {
            if (!ModelState.IsValid)
            {
                return View(order);
            }

            var result = await _orderRepository.SaveOrderAsync(order);
            if (!result)
                return View("Error");

            var orders = await _orderRepository.GetOrdersAsync();

            List<CartViewModel> cart = new List<CartViewModel>();
            Session["cart"] = cart;
 
            return PartialView("_orderListPartial", orders);
        }

        // GET: Orders/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await _orderRepository.GetOrderAsync(id.Value);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,TotalPrice")] Order order)
        {
            if (ModelState.IsValid)
            {
                await _orderRepository.SaveOrderAsync(order);
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await _orderRepository.GetOrderAsync(id.Value);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Order order = await _orderRepository.GetOrderAsync(id);
            await _orderRepository.DeleteOrderAsync(order);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult OrderListPartial()
        {
            var orders = Task.Run(() => _orderRepository.GetOrdersAsync()).Result;
            return PartialView("_orderListPartial", orders);
        }
    }
}

Projekt/ExampleMVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Example.Entities;
using Example.Entities.Models;
using Example.DataAccessLayer.Repositories.Abstract;
using ExampleMVC.Models;
using Microsoft.AspNet.Identity;

namespace ExampleMVC.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoriesRepository;
        private readonly IOrderRepository _orderRepository;
        public ProductsController(IProductRepository productRepository, ICategoryRepository categoriesRepository, IOrderRepository orderRepository)
        {
            _productRepository = productRepository;
            _categoriesRepository = categoriesRepository;
            _orderRepository = orderRepository;
        }

        // GET: Products
        public async Task<ActionResult> Index()
        {
            var products = await _productRepository.GetProductsAsync();
            return View(products);
        }

        // GET: Products/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await _productRepository.GetProductAsync(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public async Task<ActionResult> Create()
        {
            var categories = await _categoriesRepository.GetCategoriesAsync();
            ViewBag.CategoryId = new SelectList(categories, "Id", "Name");
            //ViewBag.CategoryId = new SelectList(categories, "Id", "Name", product.CategoryId);
            return View();
        }
        public async Task<ActionResult> Add(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                List<CartViewModel> cart = (List<CartViewModel>)Session["cart"];
                if(cart != null) ViewBag.Price = cart.Sum(b => b.product.Price);
                return View("Cart");
            }
            var product = await _productRepository.GetProductAsync(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            if (Session["cart"] == null)
            {
                List<CartViewModel> cart = new List<CartViewModel>();
                cart.Add(new CartViewModel(product, 1));
                Session["cart"] = cart;
                ViewBag.Price = cart.Sum(b => b.product.Price);
            }
            else 
            {
                List<CartViewModel> cart = (List<CartViewModel>)Session["cart"];
                cart.Add(new CartViewModel(product, 1));
                Session["cart"] = cart;
                ViewBag.Price = cart.Sum(b => b.product.Price);
            }    
            return View("Cart");            
        }

        public async Task<ActionResult> DeleteFromCart(int? id)
        {
            if (id == null)
            {
                ViewBag.Price = 0;
                return View("Cart");
            }
            
            if (Session["cart"] == null)
            {
                List<CartViewModel> cart = new List<CartViewModel>();
                ViewBag.Price = 0;
                Session["cart"] = cart;
            }
            else
            {
                List<CartViewModel> cart = (List<CartViewModel>)Session["cart"];
                Product product = await _productRepository.GetProductAsync(id.Value);
                cart.RemoveAt(cart.FindIndex(item => item.product.Id == id));
                Session["cart"] = cart;
                ViewBag.Price = cart.Sum(b => b.product.Price);
            }
            return View("Cart");
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Price,CategoryId")] Product product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.SaveProductAsync(product);
                return RedirectToAction("Index");
            }
            var categories = await _categoriesRepository.GetCategoriesAsync();
            ViewBag.CategoryId = new SelectList(categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await _productRepository.GetProductAsync(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }


            var categories = await _categoriesRepository.GetCategoriesAsync();
            ViewBag.CategoryId = new SelectList(categories, "Id", "Name", product.CategoryId);
            //ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Price,CategoryId")] Product product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.SaveProductAsync(product);
                return RedirectToAction("Index");
            }
            var categories = await _categoriesRepository.GetCategoriesAsync();
            ViewBag.CategoryId = new SelectList(categories, "Id", "Name", product.CategoryId);
            //ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await _productRepository.GetProductAsync(id.Value);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Product product = await _productRepository.GetProductAsync(id);
            await _productRepository.DeleteProductAsync(product);
            return RedirectToAction("Index");
        }        
    }
}

Projekt/ExampleMVC/Views/Shared/Cart.cshtml
@using ExampleMVC.Models

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Koszyk</h2>

<table class="table">
    <tr>
        <th>
            @Html.Display("Product")
        </th>
        <th>
            @Html.Display("Price")
        </th>
        <th>
            @Html.Display("Quantity")
        </th>
        <th></th>
    </tr>
    @if (ViewBag.Price != 0 && ViewBag.Price != null) {
        foreach (var item in (List<CartViewModel>)Session["cart"])
        {
            <tr>
                <td>
                    @item.product.Name
                </td>
                <td>
                    @item.product.Price
                </td>
                <td>
                    @item.quantity
                </td>
                <td>
                    @Html.ActionLink("Delete", "DeleteFromCart", "Products", new { id = item.product.Id }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
    }
    <tr>
        <th>
            <p>Total price</p>
        </th>
        <th>
            @ViewBag.Price
        </th>
        <th></th>
    </tr>
    <p>
        @Html.ActionLink("Continue shopping", "Index", "Products", new { @class = "btn btn-primary btn-sm" })
    </p>
    <p>
        @if (ViewBag.Price != 0 && ViewBag.Price != null)
        {
            <button class = "btn btn-success btn-sm" onclick="location.href='@Url.Action("Create", "Orders")';return false;"> Order</button>
            
        }
    </p>
</table>

Projekt/ExampleMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - E-Computer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E-Computer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
                        <li>@Html.ActionLink("Products", "Index", "Products")</li>
                        if (User.Identity.Name == "admin@admin.com")
                        {
                            <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                        }
                        <li>@Html.ActionLink("Cart", "Add", "Products", null, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - E-Computer</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/unobtrusive")
    @RenderSection("scripts", required: false)
</body>
</html>